# Generated by Django 5.0.4 on 2024-05-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repractical',
            name='image_id',
        ),
        migrations.AddField(
            model_name='repractical',
            name='image_id_back',
            field=models.ImageField(default='image.png', upload_to='re_practical/image_id_back'),
        ),
        migrations.AddField(
            model_name='repractical',
            name='image_id_front',
            field=models.ImageField(default='image.png', upload_to='re_practical/image_id_front'),
        ),
    ]
