# Generated by Django 5.0.4 on 2024-05-01 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=20)),
                ('type_subject', models.CharField(choices=[('إعتراض', 'إعتراض'), ('إعادة عملي', 'إعادة عملي'), ('إعادة تصحيح', 'إعادة تصحيح'), ('إختيار مواد من السنة الأعلى', 'إختيار مواد من السنة الأعلى')], max_length=40)),
                ('created_at', models.DateField()),
                ('end_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Objection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='اعتراض', max_length=20)),
                ('type_subject', models.CharField(choices=[('نظري', 'نظري'), ('عملي', 'عملي')], max_length=20)),
                ('year', models.CharField(choices=[('السنة الأولى', 'السنة الأولى'), ('السنة الثانية', 'السنة الثانية'), ('السنة الثالثة', 'السنة الثالثة'), ('السنة الرابعة', 'السنة الرابعة'), ('السنة الخامسة', 'السنة الخامسة')], max_length=20)),
                ('department', models.CharField(blank=True, choices=[('برمجيات', 'برمجيات'), ('شبكات', 'شبكات')], max_length=20, null=True)),
                ('subject', models.CharField(max_length=40)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
