# Generated by Django 5.0.4 on 2024-05-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_repractical_image_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdegreegraduation',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestdegreetransitional',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
