# Generated by Django 5.0.4 on 2024-05-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_customuser_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='objection',
            name='teacher',
            field=models.CharField(default='jacoub', max_length=40),
        ),
    ]
