# Generated by Django 5.0.4 on 2024-05-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_shoicesubject_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoicesubject',
            name='department',
            field=models.CharField(blank=True, choices=[('برمجيات', 'برمجيات'), ('شبكات', 'شبكات')], max_length=20, null=True),
        ),
    ]
