# Generated by Django 5.0.4 on 2024-05-01 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_objection_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='objection',
            name='is_refusel',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RefuselObjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=10000)),
                ('objection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.objection')),
            ],
        ),
    ]
