# Generated by Django 5.0.4 on 2024-05-02 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_objection_is_refusel_refuselobjection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoiceSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('السنة الأولى', 'السنة الأولى'), ('السنة الثانية', 'السنة الثانية'), ('السنة الثالثة', 'السنة الثالثة'), ('السنة الرابعة', 'السنة الرابعة'), ('السنة الخامسة', 'السنة الخامسة')], max_length=20)),
                ('subject', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
