# Generated by Django 5.0.4 on 2024-05-04 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_repractical'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deferment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('السنة الأولى', 'السنة الأولى'), ('السنة الثانية', 'السنة الثانية'), ('السنة الثالثة', 'السنة الثالثة'), ('السنة الرابعة', 'السنة الرابعة'), ('السنة الخامسة', 'السنة الخامسة')], max_length=20)),
                ('department', models.CharField(blank=True, choices=[('برمجيات', 'برمجيات'), ('شبكات', 'شبكات')], max_length=20, null=True)),
                ('image_id', models.ImageField(upload_to='images/ID')),
                ('image_university', models.ImageField(upload_to='images/university')),
                ('photograph', models.ImageField(upload_to='images/photograph')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permanence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('السنة الأولى', 'السنة الأولى'), ('السنة الثانية', 'السنة الثانية'), ('السنة الثالثة', 'السنة الثالثة'), ('السنة الرابعة', 'السنة الرابعة'), ('السنة الخامسة', 'السنة الخامسة')], max_length=20)),
                ('department', models.CharField(blank=True, choices=[('برمجيات', 'برمجيات'), ('شبكات', 'شبكات')], max_length=20, null=True)),
                ('image_id', models.ImageField(upload_to='images/ID')),
                ('image_university', models.ImageField(upload_to='images/university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
